# Comprehensive Indian Vegetarian Food Database (including Eggs)
# Calories are per standard serving unit listed

FOOD_DATABASE = {
    # ─── BREAKFAST ────────────────────────────────────────────────────────
    "Idli": {"calories": 80, "unit": "piece", "category": "Breakfast"},
    "Dosa (Plain)": {"calories": 150, "unit": "piece", "category": "Breakfast"},
    "Masala Dosa": {"calories": 280, "unit": "piece", "category": "Breakfast"},
    "Rava Dosa": {"calories": 170, "unit": "piece", "category": "Breakfast"},
    "Uttapam": {"calories": 200, "unit": "piece", "category": "Breakfast"},
    "Medu Vada": {"calories": 150, "unit": "piece", "category": "Breakfast"},
    "Poha": {"calories": 250, "unit": "cup", "category": "Breakfast"},
    "Upma": {"calories": 230, "unit": "cup", "category": "Breakfast"},
    "Rava Upma": {"calories": 220, "unit": "cup", "category": "Breakfast"},
    "Pongal": {"calories": 300, "unit": "cup", "category": "Breakfast"},
    "Paratha (Plain)": {"calories": 200, "unit": "piece", "category": "Breakfast"},
    "Aloo Paratha": {"calories": 280, "unit": "piece", "category": "Breakfast"},
    "Methi Paratha": {"calories": 240, "unit": "piece", "category": "Breakfast"},
    "Gobi Paratha": {"calories": 260, "unit": "piece", "category": "Breakfast"},
    "Paneer Paratha": {"calories": 300, "unit": "piece", "category": "Breakfast"},
    "Besan Cheela": {"calories": 150, "unit": "piece", "category": "Breakfast"},
    "Moong Dal Cheela": {"calories": 130, "unit": "piece", "category": "Breakfast"},
    "Bread (White)": {"calories": 75, "unit": "slice", "category": "Breakfast"},
    "Bread (Brown/Whole Wheat)": {"calories": 70, "unit": "slice", "category": "Breakfast"},
    "Bread Toast": {"calories": 80, "unit": "slice", "category": "Breakfast"},
    "Egg (Boiled)": {"calories": 78, "unit": "piece", "category": "Breakfast"},
    "Egg (Fried)": {"calories": 120, "unit": "piece", "category": "Breakfast"},
    "Omelette (2 eggs)": {"calories": 180, "unit": "serving", "category": "Breakfast"},
    "Egg Bhurji": {"calories": 200, "unit": "serving", "category": "Breakfast"},
    "Sabudana Khichdi": {"calories": 350, "unit": "cup", "category": "Breakfast"},
    "Thepla": {"calories": 160, "unit": "piece", "category": "Breakfast"},
    "Akki Roti": {"calories": 180, "unit": "piece", "category": "Breakfast"},
    "Pesarattu": {"calories": 140, "unit": "piece", "category": "Breakfast"},
    "Vermicelli Upma": {"calories": 200, "unit": "cup", "category": "Breakfast"},
    "Oats Porridge": {"calories": 150, "unit": "cup", "category": "Breakfast"},
    "Cornflakes with Milk": {"calories": 200, "unit": "bowl", "category": "Breakfast"},
    "Muesli with Milk": {"calories": 250, "unit": "bowl", "category": "Breakfast"},

    # ─── BEVERAGES ────────────────────────────────────────────────────────
    "Tea (with milk & sugar)": {"calories": 50, "unit": "cup", "category": "Beverage"},
    "Coffee (with milk & sugar)": {"calories": 65, "unit": "cup", "category": "Beverage"},
    "Black Tea": {"calories": 5, "unit": "cup", "category": "Beverage"},
    "Black Coffee": {"calories": 5, "unit": "cup", "category": "Beverage"},
    "Milk (Full Fat)": {"calories": 150, "unit": "cup", "category": "Beverage"},
    "Milk (Toned)": {"calories": 120, "unit": "cup", "category": "Beverage"},
    "Buttermilk (Chaas)": {"calories": 40, "unit": "glass", "category": "Beverage"},
    "Lassi (Sweet)": {"calories": 200, "unit": "glass", "category": "Beverage"},
    "Lassi (Salted)": {"calories": 100, "unit": "glass", "category": "Beverage"},
    "Mango Lassi": {"calories": 250, "unit": "glass", "category": "Beverage"},
    "Coconut Water": {"calories": 45, "unit": "glass", "category": "Beverage"},
    "Sugarcane Juice": {"calories": 180, "unit": "glass", "category": "Beverage"},
    "Lemon Water (with sugar)": {"calories": 60, "unit": "glass", "category": "Beverage"},
    "Nimbu Pani": {"calories": 60, "unit": "glass", "category": "Beverage"},
    "Jaljeera": {"calories": 30, "unit": "glass", "category": "Beverage"},
    "Rose Milk": {"calories": 200, "unit": "glass", "category": "Beverage"},
    "Badam Milk": {"calories": 220, "unit": "glass", "category": "Beverage"},
    "Haldi Doodh (Turmeric Milk)": {"calories": 160, "unit": "cup", "category": "Beverage"},

    # ─── RICE & GRAINS ────────────────────────────────────────────────────
    "Steamed Rice": {"calories": 200, "unit": "cup", "category": "Rice & Grains"},
    "Brown Rice": {"calories": 215, "unit": "cup", "category": "Rice & Grains"},
    "Jeera Rice": {"calories": 230, "unit": "cup", "category": "Rice & Grains"},
    "Veg Pulao": {"calories": 250, "unit": "cup", "category": "Rice & Grains"},
    "Veg Biryani": {"calories": 300, "unit": "cup", "category": "Rice & Grains"},
    "Curd Rice": {"calories": 220, "unit": "cup", "category": "Rice & Grains"},
    "Lemon Rice": {"calories": 240, "unit": "cup", "category": "Rice & Grains"},
    "Tamarind Rice (Puliyodharai)": {"calories": 260, "unit": "cup", "category": "Rice & Grains"},
    "Tomato Rice": {"calories": 240, "unit": "cup", "category": "Rice & Grains"},
    "Coconut Rice": {"calories": 280, "unit": "cup", "category": "Rice & Grains"},
    "Veg Khichdi": {"calories": 200, "unit": "cup", "category": "Rice & Grains"},
    "Egg Fried Rice": {"calories": 350, "unit": "cup", "category": "Rice & Grains"},

    # ─── BREADS ───────────────────────────────────────────────────────────
    "Roti / Chapati": {"calories": 120, "unit": "piece", "category": "Breads"},
    "Whole Wheat Roti": {"calories": 115, "unit": "piece", "category": "Breads"},
    "Tandoori Roti": {"calories": 160, "unit": "piece", "category": "Breads"},
    "Naan": {"calories": 260, "unit": "piece", "category": "Breads"},
    "Garlic Naan": {"calories": 300, "unit": "piece", "category": "Breads"},
    "Butter Naan": {"calories": 310, "unit": "piece", "category": "Breads"},
    "Puri": {"calories": 150, "unit": "piece", "category": "Breads"},
    "Bhatura": {"calories": 300, "unit": "piece", "category": "Breads"},
    "Luchi": {"calories": 140, "unit": "piece", "category": "Breads"},
    "Missi Roti": {"calories": 140, "unit": "piece", "category": "Breads"},
    "Bajra Roti": {"calories": 110, "unit": "piece", "category": "Breads"},
    "Jowar Roti": {"calories": 105, "unit": "piece", "category": "Breads"},
    "Makki di Roti": {"calories": 120, "unit": "piece", "category": "Breads"},

    # ─── DALS & LENTILS ───────────────────────────────────────────────────
    "Dal Tadka (Toor Dal)": {"calories": 180, "unit": "cup", "category": "Dal & Lentils"},
    "Dal Makhani": {"calories": 280, "unit": "cup", "category": "Dal & Lentils"},
    "Moong Dal": {"calories": 150, "unit": "cup", "category": "Dal & Lentils"},
    "Masoor Dal": {"calories": 160, "unit": "cup", "category": "Dal & Lentils"},
    "Chana Dal": {"calories": 200, "unit": "cup", "category": "Dal & Lentils"},
    "Urad Dal": {"calories": 170, "unit": "cup", "category": "Dal & Lentils"},
    "Sambar": {"calories": 130, "unit": "cup", "category": "Dal & Lentils"},
    "Rasam": {"calories": 50, "unit": "cup", "category": "Dal & Lentils"},
    "Rajma": {"calories": 250, "unit": "cup", "category": "Dal & Lentils"},
    "Chole / Chana Masala": {"calories": 270, "unit": "cup", "category": "Dal & Lentils"},
    "Moth Curry": {"calories": 200, "unit": "cup", "category": "Dal & Lentils"},
    "Peas Curry": {"calories": 180, "unit": "cup", "category": "Dal & Lentils"},

    # ─── VEGETABLE CURRIES ────────────────────────────────────────────────
    "Aloo Sabzi": {"calories": 200, "unit": "cup", "category": "Vegetable Curries"},
    "Aloo Gobi": {"calories": 180, "unit": "cup", "category": "Vegetable Curries"},
    "Aloo Matar": {"calories": 200, "unit": "cup", "category": "Vegetable Curries"},
    "Baingan Bharta": {"calories": 130, "unit": "cup", "category": "Vegetable Curries"},
    "Bhindi Masala": {"calories": 150, "unit": "cup", "category": "Vegetable Curries"},
    "Palak Curry": {"calories": 120, "unit": "cup", "category": "Vegetable Curries"},
    "Mixed Vegetable Curry": {"calories": 150, "unit": "cup", "category": "Vegetable Curries"},
    "Lauki / Bottle Gourd Curry": {"calories": 80, "unit": "cup", "category": "Vegetable Curries"},
    "Turai / Ridge Gourd Curry": {"calories": 70, "unit": "cup", "category": "Vegetable Curries"},
    "Karela / Bitter Gourd": {"calories": 90, "unit": "cup", "category": "Vegetable Curries"},
    "Cauliflower Curry": {"calories": 130, "unit": "cup", "category": "Vegetable Curries"},
    "Cabbage Sabzi": {"calories": 100, "unit": "cup", "category": "Vegetable Curries"},
    "Methi Sabzi": {"calories": 110, "unit": "cup", "category": "Vegetable Curries"},
    "Drumstick Curry": {"calories": 120, "unit": "cup", "category": "Vegetable Curries"},
    "Raw Banana Curry": {"calories": 160, "unit": "cup", "category": "Vegetable Curries"},
    "Jackfruit Curry": {"calories": 180, "unit": "cup", "category": "Vegetable Curries"},
    "Avial": {"calories": 150, "unit": "cup", "category": "Vegetable Curries"},
    "Kootu": {"calories": 160, "unit": "cup", "category": "Vegetable Curries"},
    "Poriyal (Stir fry)": {"calories": 120, "unit": "cup", "category": "Vegetable Curries"},

    # ─── PANEER & DAIRY DISHES ────────────────────────────────────────────
    "Paneer Butter Masala": {"calories": 350, "unit": "cup", "category": "Paneer & Dairy"},
    "Palak Paneer": {"calories": 280, "unit": "cup", "category": "Paneer & Dairy"},
    "Shahi Paneer": {"calories": 370, "unit": "cup", "category": "Paneer & Dairy"},
    "Paneer Tikka Masala": {"calories": 320, "unit": "cup", "category": "Paneer & Dairy"},
    "Kadai Paneer": {"calories": 310, "unit": "cup", "category": "Paneer & Dairy"},
    "Matar Paneer": {"calories": 280, "unit": "cup", "category": "Paneer & Dairy"},
    "Paneer (raw)": {"calories": 265, "unit": "100g", "category": "Paneer & Dairy"},
    "Curd / Dahi": {"calories": 60, "unit": "cup", "category": "Paneer & Dairy"},
    "Raita": {"calories": 80, "unit": "cup", "category": "Paneer & Dairy"},
    "Boondi Raita": {"calories": 120, "unit": "cup", "category": "Paneer & Dairy"},
    "Shrikhand": {"calories": 240, "unit": "cup", "category": "Paneer & Dairy"},

    # ─── EGG DISHES ───────────────────────────────────────────────────────
    "Egg Curry": {"calories": 250, "unit": "cup", "category": "Egg Dishes"},
    "Egg Masala": {"calories": 230, "unit": "cup", "category": "Egg Dishes"},
    "Egg Roast": {"calories": 200, "unit": "serving", "category": "Egg Dishes"},
    "Egg Scramble": {"calories": 180, "unit": "serving", "category": "Egg Dishes"},
    "Egg Paratha": {"calories": 350, "unit": "piece", "category": "Egg Dishes"},
    "Egg Rice": {"calories": 300, "unit": "cup", "category": "Egg Dishes"},

    # ─── SNACKS & STREET FOOD ─────────────────────────────────────────────
    "Samosa": {"calories": 250, "unit": "piece", "category": "Snacks"},
    "Kachori": {"calories": 230, "unit": "piece", "category": "Snacks"},
    "Pani Puri / Golgappa": {"calories": 200, "unit": "plate (6 pcs)", "category": "Snacks"},
    "Bhel Puri": {"calories": 180, "unit": "plate", "category": "Snacks"},
    "Sev Puri": {"calories": 200, "unit": "plate", "category": "Snacks"},
    "Dahi Puri": {"calories": 220, "unit": "plate", "category": "Snacks"},
    "Pav Bhaji": {"calories": 400, "unit": "plate", "category": "Snacks"},
    "Vada Pav": {"calories": 290, "unit": "piece", "category": "Snacks"},
    "Misal Pav": {"calories": 380, "unit": "plate", "category": "Snacks"},
    "Dabeli": {"calories": 250, "unit": "piece", "category": "Snacks"},
    "Dhokla": {"calories": 150, "unit": "2 pieces", "category": "Snacks"},
    "Khandvi": {"calories": 180, "unit": "4 pieces", "category": "Snacks"},
    "Handvo": {"calories": 200, "unit": "slice", "category": "Snacks"},
    "Chakli / Murukku": {"calories": 220, "unit": "4 pieces", "category": "Snacks"},
    "Namkeen / Mixture": {"calories": 400, "unit": "cup", "category": "Snacks"},
    "Pappad": {"calories": 50, "unit": "piece", "category": "Snacks"},
    "Roasted Peanuts": {"calories": 160, "unit": "handful", "category": "Snacks"},
    "Chikki (Peanut Brittle)": {"calories": 180, "unit": "piece", "category": "Snacks"},
    "Sev": {"calories": 400, "unit": "cup", "category": "Snacks"},
    "Corn Chaat": {"calories": 200, "unit": "cup", "category": "Snacks"},
    "Aloo Chaat": {"calories": 250, "unit": "plate", "category": "Snacks"},
    "Dahi Vada": {"calories": 220, "unit": "2 pieces", "category": "Snacks"},
    "Pakora / Bhajji": {"calories": 250, "unit": "cup", "category": "Snacks"},

    # ─── FRUITS ───────────────────────────────────────────────────────────
    "Banana": {"calories": 90, "unit": "piece", "category": "Fruits"},
    "Apple": {"calories": 80, "unit": "medium piece", "category": "Fruits"},
    "Orange": {"calories": 60, "unit": "piece", "category": "Fruits"},
    "Mango": {"calories": 100, "unit": "cup sliced", "category": "Fruits"},
    "Guava": {"calories": 50, "unit": "piece", "category": "Fruits"},
    "Papaya": {"calories": 60, "unit": "cup", "category": "Fruits"},
    "Watermelon": {"calories": 45, "unit": "cup", "category": "Fruits"},
    "Grapes": {"calories": 90, "unit": "cup", "category": "Fruits"},
    "Pomegranate": {"calories": 83, "unit": "cup", "category": "Fruits"},
    "Pineapple": {"calories": 80, "unit": "cup", "category": "Fruits"},
    "Chickoo / Sapota": {"calories": 100, "unit": "piece", "category": "Fruits"},
    "Dates": {"calories": 110, "unit": "4 pieces", "category": "Fruits"},
    "Coconut (fresh)": {"calories": 160, "unit": "cup grated", "category": "Fruits"},

    # ─── SWEETS & DESSERTS ────────────────────────────────────────────────
    "Gulab Jamun": {"calories": 175, "unit": "piece", "category": "Sweets"},
    "Rasgulla": {"calories": 120, "unit": "piece", "category": "Sweets"},
    "Rasmalai": {"calories": 150, "unit": "piece", "category": "Sweets"},
    "Ladoo (Besan)": {"calories": 200, "unit": "piece", "category": "Sweets"},
    "Ladoo (Boondi)": {"calories": 180, "unit": "piece", "category": "Sweets"},
    "Halwa (Suji/Rava)": {"calories": 350, "unit": "cup", "category": "Sweets"},
    "Halwa (Gajar/Carrot)": {"calories": 300, "unit": "cup", "category": "Sweets"},
    "Kheer / Rice Pudding": {"calories": 250, "unit": "cup", "category": "Sweets"},
    "Sevai Kheer": {"calories": 240, "unit": "cup", "category": "Sweets"},
    "Payasam": {"calories": 280, "unit": "cup", "category": "Sweets"},
    "Jalebi": {"calories": 150, "unit": "piece", "category": "Sweets"},
    "Imarti": {"calories": 200, "unit": "piece", "category": "Sweets"},
    "Peda": {"calories": 120, "unit": "piece", "category": "Sweets"},
    "Barfi (Milk Cake)": {"calories": 150, "unit": "piece", "category": "Sweets"},
    "Mysore Pak": {"calories": 200, "unit": "piece", "category": "Sweets"},
    "Kaju Katli": {"calories": 130, "unit": "piece", "category": "Sweets"},
    "Modak (Fried)": {"calories": 180, "unit": "piece", "category": "Sweets"},
    "Modak (Steamed)": {"calories": 120, "unit": "piece", "category": "Sweets"},
    "Pongal (Sweet)": {"calories": 320, "unit": "cup", "category": "Sweets"},
    "Ice Cream": {"calories": 200, "unit": "scoop", "category": "Sweets"},
    "Kulfi": {"calories": 150, "unit": "piece", "category": "Sweets"},

    # ─── SALADS & SIDES ───────────────────────────────────────────────────
    "Green Salad": {"calories": 30, "unit": "plate", "category": "Salads & Sides"},
    "Kachumber Salad": {"calories": 40, "unit": "cup", "category": "Salads & Sides"},
    "Sprouts Salad": {"calories": 100, "unit": "cup", "category": "Salads & Sides"},
    "Onion Salad": {"calories": 40, "unit": "cup", "category": "Salads & Sides"},
    "Pickle (Achar)": {"calories": 30, "unit": "tbsp", "category": "Salads & Sides"},
    "Chutney (Mint)": {"calories": 15, "unit": "tbsp", "category": "Salads & Sides"},
    "Chutney (Coconut)": {"calories": 50, "unit": "tbsp", "category": "Salads & Sides"},
    "Chutney (Tomato)": {"calories": 25, "unit": "tbsp", "category": "Salads & Sides"},
    "Pappad (Fried)": {"calories": 70, "unit": "piece", "category": "Salads & Sides"},
    "Pappad (Roasted)": {"calories": 35, "unit": "piece", "category": "Salads & Sides"},
}

MEAL_PERIODS = ["Breakfast", "Lunch", "Dinner", "Snack / Anytime"]

CATEGORIES = sorted(set(v["category"] for v in FOOD_DATABASE.values()))

def get_foods_by_category(category: str) -> dict:
    return {k: v for k, v in FOOD_DATABASE.items() if v["category"] == category}

def get_all_food_names() -> list:
    return sorted(FOOD_DATABASE.keys())

def get_food_info(food_name: str) -> dict:
    return FOOD_DATABASE.get(food_name, {})
