# Comprehensive Indian Vegetarian Food Database (including Eggs)
# Calories are per standard serving unit listed

FOOD_DATABASE = {
    # ─── BREAKFAST ────────────────────────────────────────────────────────
    "Idli": {"calories": 80, "unit": "piece", "category": "Breakfast"},
    "Dosa (Plain)": {"calories": 150, "unit": "piece", "category": "Breakfast"},
    "Masala Dosa": {"calories": 280, "unit": "piece", "category": "Breakfast"},
    "Rava Dosa": {"calories": 170, "unit": "piece", "category": "Breakfast"},
    "Rava Idli": {"calories": 110, "unit": "piece", "category": "Breakfast"},
    "Uttapam": {"calories": 200, "unit": "piece", "category": "Breakfast"},
    "Medu Vada": {"calories": 150, "unit": "piece", "category": "Breakfast"},
    "Poha": {"calories": 250, "unit": "cup", "category": "Breakfast"},
    "Kanda Poha": {"calories": 265, "unit": "cup", "category": "Breakfast"},
    "Upma": {"calories": 230, "unit": "cup", "category": "Breakfast"},
    "Rava Upma": {"calories": 220, "unit": "cup", "category": "Breakfast"},
    "Vermicelli Upma": {"calories": 200, "unit": "cup", "category": "Breakfast"},
    "Pongal (Ven Pongal)": {"calories": 300, "unit": "cup", "category": "Breakfast"},
    "Paratha (Plain)": {"calories": 200, "unit": "piece", "category": "Breakfast"},
    "Aloo Paratha": {"calories": 280, "unit": "piece", "category": "Breakfast"},
    "Methi Paratha": {"calories": 240, "unit": "piece", "category": "Breakfast"},
    "Gobi Paratha": {"calories": 260, "unit": "piece", "category": "Breakfast"},
    "Paneer Paratha": {"calories": 300, "unit": "piece", "category": "Breakfast"},
    "Sattu Paratha": {"calories": 280, "unit": "piece", "category": "Breakfast"},
    "Besan Cheela": {"calories": 150, "unit": "piece", "category": "Breakfast"},
    "Moong Dal Cheela": {"calories": 130, "unit": "piece", "category": "Breakfast"},
    "Thepla": {"calories": 160, "unit": "piece", "category": "Breakfast"},
    "Akki Roti": {"calories": 180, "unit": "piece", "category": "Breakfast"},
    "Thalipeeth": {"calories": 200, "unit": "piece", "category": "Breakfast"},
    "Pesarattu": {"calories": 140, "unit": "piece", "category": "Breakfast"},
    "Bread (White)": {"calories": 75, "unit": "slice", "category": "Breakfast"},
    "Bread (Brown/Whole Wheat)": {"calories": 70, "unit": "slice", "category": "Breakfast"},
    "Bread Toast": {"calories": 80, "unit": "slice", "category": "Breakfast"},
    "Egg (Boiled)": {"calories": 78, "unit": "piece", "category": "Breakfast"},
    "Egg (Fried)": {"calories": 120, "unit": "piece", "category": "Breakfast"},
    "Omelette (2 eggs)": {"calories": 180, "unit": "serving", "category": "Breakfast"},
    "Egg Bhurji": {"calories": 200, "unit": "serving", "category": "Breakfast"},
    "Sabudana Khichdi": {"calories": 350, "unit": "cup", "category": "Breakfast"},
    "Oats Porridge": {"calories": 150, "unit": "cup", "category": "Breakfast"},
    "Cornflakes with Milk": {"calories": 200, "unit": "bowl", "category": "Breakfast"},
    "Muesli with Milk": {"calories": 250, "unit": "bowl", "category": "Breakfast"},

    # ─── MILLETS & ANCIENT GRAINS ─────────────────────────────────────────
    # Ragi / Finger Millet
    "Ragi Mudde": {"calories": 150, "unit": "ball (medium)", "category": "Millets & Ancient Grains"},
    "Ragi Dosa": {"calories": 120, "unit": "piece", "category": "Millets & Ancient Grains"},
    "Ragi Idli": {"calories": 85, "unit": "piece", "category": "Millets & Ancient Grains"},
    "Ragi Malt / Porridge": {"calories": 150, "unit": "cup", "category": "Millets & Ancient Grains"},
    "Ragi Roti": {"calories": 120, "unit": "piece", "category": "Millets & Ancient Grains"},
    "Ragi Ladoo": {"calories": 180, "unit": "piece", "category": "Millets & Ancient Grains"},
    "Ragi Upma": {"calories": 210, "unit": "cup", "category": "Millets & Ancient Grains"},
    "Ragi Uttapam": {"calories": 190, "unit": "piece", "category": "Millets & Ancient Grains"},
    "Ragi Halwa": {"calories": 280, "unit": "cup", "category": "Millets & Ancient Grains"},
    # Bajra / Pearl Millet
    "Bajra Roti": {"calories": 110, "unit": "piece", "category": "Millets & Ancient Grains"},
    "Bajra Khichdi": {"calories": 220, "unit": "cup", "category": "Millets & Ancient Grains"},
    "Bajra Porridge (Kambu Kanji)": {"calories": 180, "unit": "cup", "category": "Millets & Ancient Grains"},
    "Bajra Dosa (Kambu Dosai)": {"calories": 130, "unit": "piece", "category": "Millets & Ancient Grains"},
    "Bajra Upma": {"calories": 200, "unit": "cup", "category": "Millets & Ancient Grains"},
    "Bajra Ladoo": {"calories": 190, "unit": "piece", "category": "Millets & Ancient Grains"},
    # Jowar / Sorghum
    "Jowar Roti": {"calories": 105, "unit": "piece", "category": "Millets & Ancient Grains"},
    "Jowar Dosa": {"calories": 130, "unit": "piece", "category": "Millets & Ancient Grains"},
    "Jowar Porridge": {"calories": 160, "unit": "cup", "category": "Millets & Ancient Grains"},
    "Jowar Upma": {"calories": 200, "unit": "cup", "category": "Millets & Ancient Grains"},
    "Jowar Pops / Jowar Popcorn": {"calories": 100, "unit": "cup", "category": "Millets & Ancient Grains"},
    # Foxtail Millet / Thinai / Kangni
    "Foxtail Millet Rice (Thinai Sadam)": {"calories": 200, "unit": "cup", "category": "Millets & Ancient Grains"},
    "Foxtail Millet Pongal": {"calories": 270, "unit": "cup", "category": "Millets & Ancient Grains"},
    "Foxtail Millet Upma (Thinai Upma)": {"calories": 210, "unit": "cup", "category": "Millets & Ancient Grains"},
    "Foxtail Millet Dosa": {"calories": 125, "unit": "piece", "category": "Millets & Ancient Grains"},
    "Foxtail Millet Khichdi": {"calories": 195, "unit": "cup", "category": "Millets & Ancient Grains"},
    # Kodo Millet / Varagu
    "Kodo Millet Rice (Varagu Sadam)": {"calories": 190, "unit": "cup", "category": "Millets & Ancient Grains"},
    "Kodo Millet Pongal": {"calories": 260, "unit": "cup", "category": "Millets & Ancient Grains"},
    "Kodo Millet Upma": {"calories": 200, "unit": "cup", "category": "Millets & Ancient Grains"},
    "Kodo Millet Dosa": {"calories": 120, "unit": "piece", "category": "Millets & Ancient Grains"},
    # Little Millet / Samai / Kutki
    "Little Millet Rice (Samai Sadam)": {"calories": 195, "unit": "cup", "category": "Millets & Ancient Grains"},
    "Little Millet Pongal": {"calories": 260, "unit": "cup", "category": "Millets & Ancient Grains"},
    "Little Millet Upma": {"calories": 205, "unit": "cup", "category": "Millets & Ancient Grains"},
    "Little Millet Idli": {"calories": 75, "unit": "piece", "category": "Millets & Ancient Grains"},
    # Barnyard Millet / Kuthiraivali / Sawa / Samo
    "Barnyard Millet Rice (Kuthiraivali)": {"calories": 200, "unit": "cup", "category": "Millets & Ancient Grains"},
    "Barnyard Millet Upma": {"calories": 210, "unit": "cup", "category": "Millets & Ancient Grains"},
    "Sama Rice (Vrat / Fasting)": {"calories": 200, "unit": "cup", "category": "Millets & Ancient Grains"},
    "Samai Pongal": {"calories": 265, "unit": "cup", "category": "Millets & Ancient Grains"},
    # Proso Millet / Panivaragu / Chena
    "Proso Millet Rice (Panivaragu)": {"calories": 205, "unit": "cup", "category": "Millets & Ancient Grains"},
    "Proso Millet Upma": {"calories": 215, "unit": "cup", "category": "Millets & Ancient Grains"},
    # Buckwheat / Kuttu
    "Kuttu Atta Roti": {"calories": 130, "unit": "piece", "category": "Millets & Ancient Grains"},
    "Kuttu Dosa": {"calories": 140, "unit": "piece", "category": "Millets & Ancient Grains"},
    "Kuttu Poori": {"calories": 160, "unit": "piece", "category": "Millets & Ancient Grains"},
    "Kuttu Khichdi": {"calories": 210, "unit": "cup", "category": "Millets & Ancient Grains"},
    # Amaranth / Rajgira
    "Rajgira Roti": {"calories": 125, "unit": "piece", "category": "Millets & Ancient Grains"},
    "Rajgira Ladoo": {"calories": 190, "unit": "piece", "category": "Millets & Ancient Grains"},
    "Rajgira Porridge": {"calories": 160, "unit": "cup", "category": "Millets & Ancient Grains"},
    # Water Chestnut / Singhara
    "Singhara Atta Roti": {"calories": 140, "unit": "piece", "category": "Millets & Ancient Grains"},
    "Singhara Halwa": {"calories": 290, "unit": "cup", "category": "Millets & Ancient Grains"},
    # Quinoa
    "Quinoa (cooked)": {"calories": 220, "unit": "cup", "category": "Millets & Ancient Grains"},
    "Quinoa Khichdi": {"calories": 230, "unit": "cup", "category": "Millets & Ancient Grains"},
    # Millet Mix
    "Multi-Millet Dosa": {"calories": 130, "unit": "piece", "category": "Millets & Ancient Grains"},
    "Multi-Millet Roti": {"calories": 115, "unit": "piece", "category": "Millets & Ancient Grains"},
    "Multi-Millet Upma": {"calories": 205, "unit": "cup", "category": "Millets & Ancient Grains"},

    # ─── BROKEN RICE, DALIA & PORRIDGES ──────────────────────────────────
    "Broken Rice Kanji / Ganji": {"calories": 120, "unit": "cup", "category": "Broken Rice & Porridges"},
    "Broken Rice Pongal": {"calories": 270, "unit": "cup", "category": "Broken Rice & Porridges"},
    "Arisi Upma (Broken Rice Upma)": {"calories": 220, "unit": "cup", "category": "Broken Rice & Porridges"},
    "Rice Kanji (Plain)": {"calories": 100, "unit": "cup", "category": "Broken Rice & Porridges"},
    "Rice Kanji (with coconut milk)": {"calories": 180, "unit": "cup", "category": "Broken Rice & Porridges"},
    "Congee / Juk (Indian style)": {"calories": 120, "unit": "cup", "category": "Broken Rice & Porridges"},
    "Panta Bhat (Fermented Rice)": {"calories": 150, "unit": "cup", "category": "Broken Rice & Porridges"},
    "Pakhala Bhata (Odisha Water Rice)": {"calories": 155, "unit": "cup", "category": "Broken Rice & Porridges"},
    "Dalia (Broken Wheat) Porridge": {"calories": 150, "unit": "cup", "category": "Broken Rice & Porridges"},
    "Dalia Khichdi": {"calories": 200, "unit": "cup", "category": "Broken Rice & Porridges"},
    "Dalia Upma": {"calories": 190, "unit": "cup", "category": "Broken Rice & Porridges"},
    "Sweet Dalia (Broken Wheat Halwa)": {"calories": 280, "unit": "cup", "category": "Broken Rice & Porridges"},
    "Wheat Porridge (Lapsi)": {"calories": 260, "unit": "cup", "category": "Broken Rice & Porridges"},
    "Moong Dal Khichdi": {"calories": 195, "unit": "cup", "category": "Broken Rice & Porridges"},
    "Masoor Dal Khichdi": {"calories": 200, "unit": "cup", "category": "Broken Rice & Porridges"},
    "Sabudana Porridge": {"calories": 250, "unit": "cup", "category": "Broken Rice & Porridges"},
    "Oats Khichdi": {"calories": 200, "unit": "cup", "category": "Broken Rice & Porridges"},
    "Oats Dosa": {"calories": 130, "unit": "piece", "category": "Broken Rice & Porridges"},
    "Oats Idli": {"calories": 90, "unit": "piece", "category": "Broken Rice & Porridges"},
    "Ragi Porridge (for infants/all age)": {"calories": 140, "unit": "cup", "category": "Broken Rice & Porridges"},
    "Sattu Drink (sweet)": {"calories": 150, "unit": "glass", "category": "Broken Rice & Porridges"},
    "Sattu Drink (salted)": {"calories": 130, "unit": "glass", "category": "Broken Rice & Porridges"},
    "Corn Porridge (Makka Kanji)": {"calories": 160, "unit": "cup", "category": "Broken Rice & Porridges"},

    # ─── BEVERAGES ────────────────────────────────────────────────────────
    # Teas
    "Tea (with milk & sugar)": {"calories": 50, "unit": "cup", "category": "Beverage"},
    "Masala Chai": {"calories": 60, "unit": "cup", "category": "Beverage"},
    "Filter Coffee": {"calories": 60, "unit": "cup", "category": "Beverage"},
    "Coffee (with milk & sugar)": {"calories": 65, "unit": "cup", "category": "Beverage"},
    "Black Tea": {"calories": 5, "unit": "cup", "category": "Beverage"},
    "Black Coffee": {"calories": 5, "unit": "cup", "category": "Beverage"},
    "Green Tea (plain)": {"calories": 2, "unit": "cup", "category": "Beverage"},
    "Green Tea (with honey)": {"calories": 25, "unit": "cup", "category": "Beverage"},
    "Herbal Tea (Tulsi / Ginger)": {"calories": 5, "unit": "cup", "category": "Beverage"},
    "Chamomile Tea": {"calories": 2, "unit": "cup", "category": "Beverage"},
    "Peppermint Tea": {"calories": 2, "unit": "cup", "category": "Beverage"},
    "Lemon Tea": {"calories": 10, "unit": "cup", "category": "Beverage"},
    "Kashmiri Kahwa": {"calories": 45, "unit": "cup", "category": "Beverage"},
    "Cold Coffee (with milk)": {"calories": 120, "unit": "glass", "category": "Beverage"},
    "Iced Tea (sweetened)": {"calories": 90, "unit": "glass", "category": "Beverage"},
    # Milk & milk drinks
    "Milk (Full Fat)": {"calories": 150, "unit": "cup", "category": "Beverage"},
    "Milk (Toned)": {"calories": 120, "unit": "cup", "category": "Beverage"},
    "Almond Milk": {"calories": 60, "unit": "cup", "category": "Beverage"},
    "Soy Milk": {"calories": 100, "unit": "cup", "category": "Beverage"},
    "Oat Milk": {"calories": 120, "unit": "cup", "category": "Beverage"},
    "Horlicks with Milk": {"calories": 180, "unit": "cup", "category": "Beverage"},
    "Bournvita with Milk": {"calories": 190, "unit": "cup", "category": "Beverage"},
    "Complan with Milk": {"calories": 170, "unit": "cup", "category": "Beverage"},
    "Flavored Milk (Amul Kool)": {"calories": 160, "unit": "200ml pack", "category": "Beverage"},
    "Badam Milk": {"calories": 220, "unit": "glass", "category": "Beverage"},
    "Rose Milk": {"calories": 200, "unit": "glass", "category": "Beverage"},
    "Haldi Doodh (Turmeric Milk)": {"calories": 160, "unit": "cup", "category": "Beverage"},
    # Yoghurt / fermented
    "Buttermilk (Chaas)": {"calories": 40, "unit": "glass", "category": "Beverage"},
    "Lassi (Sweet)": {"calories": 200, "unit": "glass", "category": "Beverage"},
    "Lassi (Salted)": {"calories": 100, "unit": "glass", "category": "Beverage"},
    "Mango Lassi": {"calories": 250, "unit": "glass", "category": "Beverage"},
    # Fresh juices
    "Fresh Orange Juice": {"calories": 110, "unit": "glass", "category": "Beverage"},
    "Fresh Mango Juice": {"calories": 130, "unit": "glass", "category": "Beverage"},
    "Fresh Apple Juice": {"calories": 120, "unit": "glass", "category": "Beverage"},
    "Fresh Pineapple Juice": {"calories": 130, "unit": "glass", "category": "Beverage"},
    "Fresh Watermelon Juice": {"calories": 80, "unit": "glass", "category": "Beverage"},
    "Fresh Pomegranate Juice": {"calories": 135, "unit": "glass", "category": "Beverage"},
    "Fresh Carrot Juice": {"calories": 95, "unit": "glass", "category": "Beverage"},
    "Fresh Beetroot Juice": {"calories": 100, "unit": "glass", "category": "Beverage"},
    "Fresh Tomato Juice": {"calories": 40, "unit": "glass", "category": "Beverage"},
    "Mixed Fruit Juice": {"calories": 120, "unit": "glass", "category": "Beverage"},
    "Green Smoothie (spinach/banana)": {"calories": 150, "unit": "glass", "category": "Beverage"},
    "Packaged Fruit Juice (Tropicana)": {"calories": 110, "unit": "200ml pack", "category": "Beverage"},
    # Milkshakes
    "Banana Milkshake": {"calories": 280, "unit": "glass", "category": "Beverage"},
    "Mango Milkshake": {"calories": 250, "unit": "glass", "category": "Beverage"},
    "Chocolate Milkshake": {"calories": 300, "unit": "glass", "category": "Beverage"},
    "Strawberry Milkshake": {"calories": 240, "unit": "glass", "category": "Beverage"},
    # Other drinks
    "Coconut Water": {"calories": 45, "unit": "glass", "category": "Beverage"},
    "Sugarcane Juice": {"calories": 180, "unit": "glass", "category": "Beverage"},
    "Lemon Water (with sugar)": {"calories": 60, "unit": "glass", "category": "Beverage"},
    "Nimbu Pani": {"calories": 60, "unit": "glass", "category": "Beverage"},
    "Jaljeera": {"calories": 30, "unit": "glass", "category": "Beverage"},
    "Aam Panna": {"calories": 70, "unit": "glass", "category": "Beverage"},
    "Tamarind Juice (Imli Pani)": {"calories": 55, "unit": "glass", "category": "Beverage"},
    "Panakam (Jaggery lemon drink)": {"calories": 80, "unit": "glass", "category": "Beverage"},
    "Thandai": {"calories": 180, "unit": "glass", "category": "Beverage"},
    "Sherbat (Rose/Khus/Rooh Afza)": {"calories": 95, "unit": "glass", "category": "Beverage"},
    "Nannari Sharbat": {"calories": 100, "unit": "glass", "category": "Beverage"},
    "Sol Kadhi": {"calories": 80, "unit": "glass", "category": "Beverage"},
    # Soft drinks / carbonated
    "Cola (Pepsi / Coke) 350ml": {"calories": 140, "unit": "can", "category": "Beverage"},
    "Sprite / Limca 350ml": {"calories": 140, "unit": "can", "category": "Beverage"},
    "Thums Up 350ml": {"calories": 145, "unit": "can", "category": "Beverage"},
    "Soda Water (plain)": {"calories": 0, "unit": "glass", "category": "Beverage"},
    "Energy Drink (Red Bull type)": {"calories": 110, "unit": "250ml can", "category": "Beverage"},
    "Protein Shake (whey with milk)": {"calories": 300, "unit": "glass", "category": "Beverage"},

    # ─── RICE & GRAINS ────────────────────────────────────────────────────
    "Steamed Rice": {"calories": 200, "unit": "cup", "category": "Rice & Grains"},
    "Brown Rice": {"calories": 215, "unit": "cup", "category": "Rice & Grains"},
    "Red Rice / Matta Rice": {"calories": 210, "unit": "cup", "category": "Rice & Grains"},
    "Black Rice": {"calories": 215, "unit": "cup", "category": "Rice & Grains"},
    "Jeera Rice": {"calories": 230, "unit": "cup", "category": "Rice & Grains"},
    "Veg Pulao": {"calories": 250, "unit": "cup", "category": "Rice & Grains"},
    "Veg Biryani": {"calories": 300, "unit": "cup", "category": "Rice & Grains"},
    "Curd Rice": {"calories": 220, "unit": "cup", "category": "Rice & Grains"},
    "Lemon Rice": {"calories": 240, "unit": "cup", "category": "Rice & Grains"},
    "Tamarind Rice (Puliyodharai)": {"calories": 260, "unit": "cup", "category": "Rice & Grains"},
    "Tomato Rice": {"calories": 240, "unit": "cup", "category": "Rice & Grains"},
    "Coconut Rice": {"calories": 280, "unit": "cup", "category": "Rice & Grains"},
    "Veg Khichdi": {"calories": 200, "unit": "cup", "category": "Rice & Grains"},
    "Egg Fried Rice": {"calories": 350, "unit": "cup", "category": "Rice & Grains"},
    "Ghee Rice (Neyyi Annam)": {"calories": 280, "unit": "cup", "category": "Rice & Grains"},
    "Bisi Bele Bath": {"calories": 300, "unit": "cup", "category": "Rice & Grains"},
    "Vangi Bath": {"calories": 250, "unit": "cup", "category": "Rice & Grains"},
    "Chitranna (Karnataka Lemon Rice)": {"calories": 245, "unit": "cup", "category": "Rice & Grains"},
    "Khichuri (Bengali)": {"calories": 220, "unit": "cup", "category": "Rice & Grains"},
    "Veg Tehri": {"calories": 260, "unit": "cup", "category": "Rice & Grains"},
    "Capsicum Rice": {"calories": 235, "unit": "cup", "category": "Rice & Grains"},
    "Palak Rice": {"calories": 230, "unit": "cup", "category": "Rice & Grains"},
    "Egg Biryani": {"calories": 360, "unit": "cup", "category": "Rice & Grains"},

    # ─── BREADS ───────────────────────────────────────────────────────────
    "Roti / Chapati": {"calories": 120, "unit": "piece", "category": "Breads"},
    "Whole Wheat Roti": {"calories": 115, "unit": "piece", "category": "Breads"},
    "Tandoori Roti": {"calories": 160, "unit": "piece", "category": "Breads"},
    "Naan": {"calories": 260, "unit": "piece", "category": "Breads"},
    "Garlic Naan": {"calories": 300, "unit": "piece", "category": "Breads"},
    "Butter Naan": {"calories": 310, "unit": "piece", "category": "Breads"},
    "Puri": {"calories": 150, "unit": "piece", "category": "Breads"},
    "Bhatura": {"calories": 300, "unit": "piece", "category": "Breads"},
    "Luchi": {"calories": 140, "unit": "piece", "category": "Breads"},
    "Missi Roti": {"calories": 140, "unit": "piece", "category": "Breads"},
    "Makki di Roti": {"calories": 120, "unit": "piece", "category": "Breads"},
    "Amritsari Kulcha": {"calories": 300, "unit": "piece", "category": "Breads"},
    "Aloo Kulcha": {"calories": 280, "unit": "piece", "category": "Breads"},
    "Bedmi Puri": {"calories": 180, "unit": "piece", "category": "Breads"},
    "Dal Puri": {"calories": 250, "unit": "piece", "category": "Breads"},
    "Baati (plain)": {"calories": 250, "unit": "piece", "category": "Breads"},
    "Kerala Parotta": {"calories": 260, "unit": "piece", "category": "Breads"},
    "Appam": {"calories": 120, "unit": "piece", "category": "Breads"},
    "Idiyappam / String Hoppers": {"calories": 80, "unit": "2 pieces", "category": "Breads"},
    "Puttu": {"calories": 200, "unit": "serving", "category": "Breads"},
    "Poori (small)": {"calories": 130, "unit": "piece", "category": "Breads"},

    # ─── DALS & LENTILS ───────────────────────────────────────────────────
    "Dal Tadka (Toor Dal)": {"calories": 180, "unit": "cup", "category": "Dal & Lentils"},
    "Dal Makhani": {"calories": 280, "unit": "cup", "category": "Dal & Lentils"},
    "Moong Dal": {"calories": 150, "unit": "cup", "category": "Dal & Lentils"},
    "Masoor Dal": {"calories": 160, "unit": "cup", "category": "Dal & Lentils"},
    "Chana Dal": {"calories": 200, "unit": "cup", "category": "Dal & Lentils"},
    "Urad Dal": {"calories": 170, "unit": "cup", "category": "Dal & Lentils"},
    "Sambar": {"calories": 130, "unit": "cup", "category": "Dal & Lentils"},
    "Rasam": {"calories": 50, "unit": "cup", "category": "Dal & Lentils"},
    "Rajma": {"calories": 250, "unit": "cup", "category": "Dal & Lentils"},
    "Chole / Chana Masala": {"calories": 270, "unit": "cup", "category": "Dal & Lentils"},
    "Moth Curry": {"calories": 200, "unit": "cup", "category": "Dal & Lentils"},
    "Peas Curry": {"calories": 180, "unit": "cup", "category": "Dal & Lentils"},
    "Cholar Dal (Bengali Chana Dal)": {"calories": 250, "unit": "cup", "category": "Dal & Lentils"},
    "Dalma (Odisha Dal with veg)": {"calories": 200, "unit": "cup", "category": "Dal & Lentils"},
    "Mudda Pappu (Plain Toor Dal AP)": {"calories": 170, "unit": "cup", "category": "Dal & Lentils"},
    "Gongura Dal": {"calories": 200, "unit": "cup", "category": "Dal & Lentils"},
    "Dosakaya Dal (Cucumber Dal)": {"calories": 160, "unit": "cup", "category": "Dal & Lentils"},
    "Pithla / Zunka": {"calories": 180, "unit": "cup", "category": "Dal & Lentils"},
    "Ghugni (Yellow Peas Curry)": {"calories": 200, "unit": "cup", "category": "Dal & Lentils"},
    "Sundal (Chana)": {"calories": 150, "unit": "cup", "category": "Dal & Lentils"},
    "Sundal (Moong)": {"calories": 130, "unit": "cup", "category": "Dal & Lentils"},
    "Sundal (Rajma)": {"calories": 160, "unit": "cup", "category": "Dal & Lentils"},
    "Kadala Curry": {"calories": 250, "unit": "cup", "category": "Dal & Lentils"},
    "Mysore Rasam": {"calories": 60, "unit": "cup", "category": "Dal & Lentils"},
    "Tomato Rasam": {"calories": 55, "unit": "cup", "category": "Dal & Lentils"},
    "Pepper Rasam": {"calories": 45, "unit": "cup", "category": "Dal & Lentils"},

    # ─── VEGETABLE CURRIES ────────────────────────────────────────────────
    "Aloo Sabzi": {"calories": 200, "unit": "cup", "category": "Vegetable Curries"},
    "Aloo Gobi": {"calories": 180, "unit": "cup", "category": "Vegetable Curries"},
    "Aloo Matar": {"calories": 200, "unit": "cup", "category": "Vegetable Curries"},
    "Baingan Bharta": {"calories": 130, "unit": "cup", "category": "Vegetable Curries"},
    "Bhindi Masala": {"calories": 150, "unit": "cup", "category": "Vegetable Curries"},
    "Palak Curry": {"calories": 120, "unit": "cup", "category": "Vegetable Curries"},
    "Mixed Vegetable Curry": {"calories": 150, "unit": "cup", "category": "Vegetable Curries"},
    "Lauki / Bottle Gourd Curry": {"calories": 80, "unit": "cup", "category": "Vegetable Curries"},
    "Turai / Ridge Gourd Curry": {"calories": 70, "unit": "cup", "category": "Vegetable Curries"},
    "Karela / Bitter Gourd": {"calories": 90, "unit": "cup", "category": "Vegetable Curries"},
    "Cauliflower Curry": {"calories": 130, "unit": "cup", "category": "Vegetable Curries"},
    "Cabbage Sabzi": {"calories": 100, "unit": "cup", "category": "Vegetable Curries"},
    "Methi Sabzi": {"calories": 110, "unit": "cup", "category": "Vegetable Curries"},
    "Drumstick Curry": {"calories": 120, "unit": "cup", "category": "Vegetable Curries"},
    "Raw Banana Curry": {"calories": 160, "unit": "cup", "category": "Vegetable Curries"},
    "Jackfruit Curry (Kathal)": {"calories": 180, "unit": "cup", "category": "Vegetable Curries"},
    "Avial": {"calories": 150, "unit": "cup", "category": "Vegetable Curries"},
    "Kootu (Tamil Nadu)": {"calories": 160, "unit": "cup", "category": "Vegetable Curries"},
    "Poriyal / Stir Fry": {"calories": 120, "unit": "cup", "category": "Vegetable Curries"},
    "Thoran (Kerala stir fry)": {"calories": 120, "unit": "cup", "category": "Vegetable Curries"},
    "Olan (Pumpkin & Coconut milk)": {"calories": 100, "unit": "cup", "category": "Vegetable Curries"},
    "Erissery (Pumpkin & Lentil)": {"calories": 180, "unit": "cup", "category": "Vegetable Curries"},
    "Kalan (Raw Banana Yoghurt)": {"calories": 200, "unit": "cup", "category": "Vegetable Curries"},
    "Pulissery (Mor Kuzhambu Kerala)": {"calories": 100, "unit": "cup", "category": "Vegetable Curries"},
    "Mor Kuzhambu": {"calories": 100, "unit": "cup", "category": "Vegetable Curries"},
    "Vatha Kuzhambu": {"calories": 150, "unit": "cup", "category": "Vegetable Curries"},
    "Puli Kuzhambu": {"calories": 140, "unit": "cup", "category": "Vegetable Curries"},
    "Poricha Kuzhambu": {"calories": 140, "unit": "cup", "category": "Vegetable Curries"},
    "Pachadi (Kerala)": {"calories": 80, "unit": "cup", "category": "Vegetable Curries"},
    "Gutti Vankaya (Stuffed Brinjal AP)": {"calories": 250, "unit": "cup", "category": "Vegetable Curries"},
    "Vankaya Curry (AP Brinjal)": {"calories": 150, "unit": "cup", "category": "Vegetable Curries"},
    "Aloo Posto (Bengali)": {"calories": 200, "unit": "cup", "category": "Vegetable Curries"},
    "Begun Bhaja (Fried Brinjal)": {"calories": 150, "unit": "cup", "category": "Vegetable Curries"},
    "Santula (Odisha Stir Fry)": {"calories": 100, "unit": "cup", "category": "Vegetable Curries"},
    "Sarson Da Saag": {"calories": 150, "unit": "cup", "category": "Vegetable Curries"},
    "Undhiyu": {"calories": 250, "unit": "cup", "category": "Vegetable Curries"},
    "Bharli Vangi (Maha stuffed Brinjal)": {"calories": 200, "unit": "cup", "category": "Vegetable Curries"},
    "Gatte ki Sabzi": {"calories": 250, "unit": "cup", "category": "Vegetable Curries"},
    "Ker Sangri": {"calories": 150, "unit": "cup", "category": "Vegetable Curries"},
    "Ennegayi (Karnataka)": {"calories": 250, "unit": "cup", "category": "Vegetable Curries"},
    "Ringan Vatana (Brinjal Peas Guj)": {"calories": 180, "unit": "cup", "category": "Vegetable Curries"},
    "Sev Tameta (Tomato Sev Guj)": {"calories": 180, "unit": "cup", "category": "Vegetable Curries"},
    "Chokha (Bihar)": {"calories": 100, "unit": "cup", "category": "Vegetable Curries"},
    "Cauliflower Bhaaji": {"calories": 130, "unit": "cup", "category": "Vegetable Curries"},
    "Mushroom Masala": {"calories": 180, "unit": "cup", "category": "Vegetable Curries"},
    "Baby Corn Masala": {"calories": 160, "unit": "cup", "category": "Vegetable Curries"},
    "Capsicum Masala": {"calories": 150, "unit": "cup", "category": "Vegetable Curries"},
    "Tomato Curry": {"calories": 120, "unit": "cup", "category": "Vegetable Curries"},
    "Snake Gourd Curry": {"calories": 70, "unit": "cup", "category": "Vegetable Curries"},
    "Ash Gourd Curry": {"calories": 60, "unit": "cup", "category": "Vegetable Curries"},
    "Cluster Beans (Guar) Sabzi": {"calories": 90, "unit": "cup", "category": "Vegetable Curries"},
    "Broad Beans (Papdi) Sabzi": {"calories": 110, "unit": "cup", "category": "Vegetable Curries"},
    "Tindora / Ivy Gourd Sabzi": {"calories": 80, "unit": "cup", "category": "Vegetable Curries"},
    "Parwal / Pointed Gourd Sabzi": {"calories": 90, "unit": "cup", "category": "Vegetable Curries"},

    # ─── PANEER & DAIRY DISHES ────────────────────────────────────────────
    "Paneer Butter Masala": {"calories": 350, "unit": "cup", "category": "Paneer & Dairy"},
    "Palak Paneer": {"calories": 280, "unit": "cup", "category": "Paneer & Dairy"},
    "Shahi Paneer": {"calories": 370, "unit": "cup", "category": "Paneer & Dairy"},
    "Paneer Tikka Masala": {"calories": 320, "unit": "cup", "category": "Paneer & Dairy"},
    "Kadai Paneer": {"calories": 310, "unit": "cup", "category": "Paneer & Dairy"},
    "Matar Paneer": {"calories": 280, "unit": "cup", "category": "Paneer & Dairy"},
    "Paneer Bhurji": {"calories": 250, "unit": "cup", "category": "Paneer & Dairy"},
    "Achari Paneer": {"calories": 300, "unit": "cup", "category": "Paneer & Dairy"},
    "Sorshe Paneer (Mustard Paneer)": {"calories": 280, "unit": "cup", "category": "Paneer & Dairy"},
    "Paneer (raw)": {"calories": 265, "unit": "100g", "category": "Paneer & Dairy"},
    "Curd / Dahi": {"calories": 60, "unit": "cup", "category": "Paneer & Dairy"},
    "Raita": {"calories": 80, "unit": "cup", "category": "Paneer & Dairy"},
    "Boondi Raita": {"calories": 120, "unit": "cup", "category": "Paneer & Dairy"},
    "Cucumber Raita": {"calories": 75, "unit": "cup", "category": "Paneer & Dairy"},
    "Shrikhand": {"calories": 240, "unit": "cup", "category": "Paneer & Dairy"},
    "Mishti Doi (Sweet Curd Bengal)": {"calories": 150, "unit": "cup", "category": "Paneer & Dairy"},
    "Basundi": {"calories": 280, "unit": "cup", "category": "Paneer & Dairy"},
    "Rabri": {"calories": 300, "unit": "cup", "category": "Paneer & Dairy"},
    "Greek Yogurt (plain)": {"calories": 100, "unit": "cup", "category": "Paneer & Dairy"},
    "Flavored Yogurt (fruit)": {"calories": 150, "unit": "cup", "category": "Paneer & Dairy"},
    "Khoya / Mawa": {"calories": 450, "unit": "100g", "category": "Paneer & Dairy"},
    "Condensed Milk": {"calories": 130, "unit": "tbsp", "category": "Paneer & Dairy"},
    "Cream (fresh)": {"calories": 100, "unit": "tbsp", "category": "Paneer & Dairy"},
    "Cheese Slice": {"calories": 70, "unit": "slice", "category": "Paneer & Dairy"},
    "Cheese Spread": {"calories": 80, "unit": "tbsp", "category": "Paneer & Dairy"},

    # ─── EGG DISHES ───────────────────────────────────────────────────────
    "Egg Curry": {"calories": 250, "unit": "cup", "category": "Egg Dishes"},
    "Egg Masala": {"calories": 230, "unit": "cup", "category": "Egg Dishes"},
    "Egg Roast": {"calories": 200, "unit": "serving", "category": "Egg Dishes"},
    "Egg Scramble": {"calories": 180, "unit": "serving", "category": "Egg Dishes"},
    "Egg Paratha": {"calories": 350, "unit": "piece", "category": "Egg Dishes"},
    "Egg Rice": {"calories": 300, "unit": "cup", "category": "Egg Dishes"},
    "Egg Dosa": {"calories": 220, "unit": "piece", "category": "Egg Dishes"},
    "Egg Uttapam": {"calories": 230, "unit": "piece", "category": "Egg Dishes"},
    "Egg Podimas (Tamil Nadu)": {"calories": 190, "unit": "serving", "category": "Egg Dishes"},
    "Egg Kothu Parotta": {"calories": 450, "unit": "plate", "category": "Egg Dishes"},

    # ─── REGIONAL — SOUTH INDIA ───────────────────────────────────────────
    "Litti Chokha": {"calories": 400, "unit": "serving (2 litti)", "category": "Regional - North India"},
    "Appam with Stew": {"calories": 280, "unit": "serving", "category": "Regional - South India"},
    "Puttu with Kadala Curry": {"calories": 380, "unit": "serving", "category": "Regional - South India"},
    "Idiyappam with Coconut Milk": {"calories": 200, "unit": "serving", "category": "Regional - South India"},
    "Kozhukattai (Modak steamed)": {"calories": 120, "unit": "piece", "category": "Regional - South India"},
    "Nei Appam (Sweet Appam)": {"calories": 160, "unit": "piece", "category": "Regional - South India"},
    "Paniyaram": {"calories": 80, "unit": "piece", "category": "Regional - South India"},
    "Adai (Mixed Lentil Dosa)": {"calories": 160, "unit": "piece", "category": "Regional - South India"},
    "Kuzhi Paniyaram": {"calories": 90, "unit": "piece", "category": "Regional - South India"},
    "Chettinad Kuzhambu": {"calories": 200, "unit": "cup", "category": "Regional - South India"},
    "Kottu Parotta (Veg)": {"calories": 400, "unit": "plate", "category": "Regional - South India"},
    "Parotta (Malabar)": {"calories": 250, "unit": "piece", "category": "Regional - South India"},
    "Pesarattu with Upma": {"calories": 280, "unit": "serving", "category": "Regional - South India"},
    "Sakinalu": {"calories": 200, "unit": "cup", "category": "Regional - South India"},
    "Pulihora (Andhra Tamarind Rice)": {"calories": 265, "unit": "cup", "category": "Regional - South India"},
    "Punugulu": {"calories": 200, "unit": "6 pieces", "category": "Regional - South India"},
    "Mysore Bonda": {"calories": 180, "unit": "3 pieces", "category": "Regional - South India"},
    "Mangalore Buns": {"calories": 200, "unit": "piece", "category": "Regional - South India"},
    "Neer Dosa": {"calories": 80, "unit": "piece", "category": "Regional - South India"},
    "Kundapura Koli Saaru (Veg Saaru)": {"calories": 100, "unit": "cup", "category": "Regional - South India"},
    "Saaru / Karnataka Rasam": {"calories": 60, "unit": "cup", "category": "Regional - South India"},
    "Avalakki (Karnataka Poha)": {"calories": 255, "unit": "cup", "category": "Regional - South India"},
    "Ambode (Chana Dal Vada)": {"calories": 170, "unit": "piece", "category": "Regional - South India"},
    "Nippattu": {"calories": 200, "unit": "4 pieces", "category": "Regional - South India"},
    "Kodubale": {"calories": 220, "unit": "4 pieces", "category": "Regional - South India"},
    "Kobbari Mithai (Coconut Burfi)": {"calories": 160, "unit": "piece", "category": "Regional - South India"},
    "Paal Payasam (Tamil/Kerala)": {"calories": 250, "unit": "cup", "category": "Regional - South India"},
    "Semiya Payasam": {"calories": 240, "unit": "cup", "category": "Regional - South India"},
    "Moong Dal Payasam": {"calories": 270, "unit": "cup", "category": "Regional - South India"},
    "Chakkarai Pongal (Sweet Pongal)": {"calories": 320, "unit": "cup", "category": "Regional - South India"},
    "Adhirasam": {"calories": 200, "unit": "piece", "category": "Regional - South India"},
    "Murukku": {"calories": 220, "unit": "4 pieces", "category": "Regional - South India"},
    "Ribbon Pakoda": {"calories": 210, "unit": "cup", "category": "Regional - South India"},
    "Thattai": {"calories": 180, "unit": "4 pieces", "category": "Regional - South India"},
    "Seedai": {"calories": 200, "unit": "cup", "category": "Regional - South India"},
    "Sunnundalu (Andhra Ladoo)": {"calories": 180, "unit": "piece", "category": "Regional - South India"},
    "Ariselu (Andhra Sweet)": {"calories": 190, "unit": "piece", "category": "Regional - South India"},
    "Bobbatlu / Puran Poli (AP)": {"calories": 260, "unit": "piece", "category": "Regional - South India"},
    "Pootharekulu (Andhra)": {"calories": 170, "unit": "piece", "category": "Regional - South India"},

    # ─── REGIONAL — NORTH INDIA ───────────────────────────────────────────
    "Dal Baati Churma": {"calories": 600, "unit": "serving (2 baati)", "category": "Regional - North India"},
    "Churma": {"calories": 400, "unit": "cup", "category": "Regional - North India"},
    "Besan Gatta Curry": {"calories": 250, "unit": "cup", "category": "Regional - North India"},
    "Pyaaz Kachori": {"calories": 300, "unit": "piece", "category": "Regional - North India"},
    "Mawa Kachori": {"calories": 350, "unit": "piece", "category": "Regional - North India"},
    "Pinni (Punjab sweet)": {"calories": 250, "unit": "piece", "category": "Regional - North India"},
    "Karah Prasad": {"calories": 300, "unit": "cup", "category": "Regional - North India"},
    "Amritsari Paneer Bhurji": {"calories": 270, "unit": "cup", "category": "Regional - North India"},
    "Thekua (Bihar)": {"calories": 180, "unit": "piece", "category": "Regional - North India"},
    "Khaja (Bihar sweet)": {"calories": 200, "unit": "piece", "category": "Regional - North India"},
    "Malpua": {"calories": 200, "unit": "piece", "category": "Regional - North India"},
    "Bedai (UP Breakfast)": {"calories": 250, "unit": "piece", "category": "Regional - North India"},
    "Aloo Tikki": {"calories": 180, "unit": "piece", "category": "Regional - North India"},
    "Dahi Bhalla": {"calories": 220, "unit": "2 pieces", "category": "Regional - North India"},
    "Gol Gappe / Pani Puri": {"calories": 200, "unit": "plate (6 pcs)", "category": "Regional - North India"},
    "Papri Chaat": {"calories": 280, "unit": "plate", "category": "Regional - North India"},
    "Ram Ladoo": {"calories": 160, "unit": "2 pieces", "category": "Regional - North India"},
    "Chana Jor Garam": {"calories": 180, "unit": "cup", "category": "Regional - North India"},
    "Matar Kulcha": {"calories": 350, "unit": "serving", "category": "Regional - North India"},
    "Chole Bhature": {"calories": 600, "unit": "plate (2 bhature)", "category": "Regional - North India"},
    "Shahi Tukda": {"calories": 300, "unit": "piece", "category": "Regional - North India"},
    "Balushahi": {"calories": 200, "unit": "piece", "category": "Regional - North India"},
    "Ghevar": {"calories": 280, "unit": "piece", "category": "Regional - North India"},
    "Moong Dal Halwa": {"calories": 380, "unit": "cup", "category": "Regional - North India"},
    "Atta Halwa": {"calories": 360, "unit": "cup", "category": "Regional - North India"},
    "Chana Dal Halwa": {"calories": 370, "unit": "cup", "category": "Regional - North India"},
    "Gond Ladoo": {"calories": 220, "unit": "piece", "category": "Regional - North India"},
    "Til Ladoo (Sesame)": {"calories": 200, "unit": "piece", "category": "Regional - North India"},
    "Rewri (Sesame brittle)": {"calories": 170, "unit": "4 pieces", "category": "Regional - North India"},
    "Gajak": {"calories": 180, "unit": "piece", "category": "Regional - North India"},

    # ─── REGIONAL — WEST INDIA (GUJARAT & MAHARASHTRA) ───────────────────
    "Surti Locho": {"calories": 300, "unit": "serving", "category": "Regional - West India"},
    "Fafda with Jalebi": {"calories": 350, "unit": "serving", "category": "Regional - West India"},
    "Fafda": {"calories": 180, "unit": "serving", "category": "Regional - West India"},
    "Gathiya": {"calories": 200, "unit": "serving", "category": "Regional - West India"},
    "Methi Muthia": {"calories": 150, "unit": "4 pieces", "category": "Regional - West India"},
    "Mohanthal": {"calories": 300, "unit": "piece", "category": "Regional - West India"},
    "Aamras": {"calories": 120, "unit": "cup", "category": "Regional - West India"},
    "Aamras Puri": {"calories": 400, "unit": "serving", "category": "Regional - West India"},
    "Gujarati Thali (full)": {"calories": 800, "unit": "thali", "category": "Regional - West India"},
    "Puran Poli": {"calories": 260, "unit": "piece", "category": "Regional - West India"},
    "Batata Vada": {"calories": 200, "unit": "piece", "category": "Regional - West India"},
    "Bhakri (Jowar)": {"calories": 105, "unit": "piece", "category": "Regional - West India"},
    "Bhakri (Bajra)": {"calories": 110, "unit": "piece", "category": "Regional - West India"},
    "Pitla (Besan Curry)": {"calories": 150, "unit": "cup", "category": "Regional - West India"},
    "Bharit (Maha Baingan Bharta)": {"calories": 120, "unit": "cup", "category": "Regional - West India"},
    "Sabudana Vada": {"calories": 180, "unit": "piece", "category": "Regional - West India"},
    "Kanda Bhajji (Onion Pakora)": {"calories": 220, "unit": "cup", "category": "Regional - West India"},
    "Shreekhand": {"calories": 250, "unit": "cup", "category": "Regional - West India"},
    "Basundi (Maha)": {"calories": 280, "unit": "cup", "category": "Regional - West India"},

    # ─── REGIONAL — EAST INDIA (BENGAL & ODISHA) ─────────────────────────
    "Sandesh": {"calories": 120, "unit": "piece", "category": "Regional - East India"},
    "Chhena Poda (Odisha)": {"calories": 300, "unit": "piece", "category": "Regional - East India"},
    "Rasabali (Odisha)": {"calories": 200, "unit": "piece", "category": "Regional - East India"},
    "Chenna Gaja (Odisha)": {"calories": 250, "unit": "piece", "category": "Regional - East India"},
    "Malpua (Bengal)": {"calories": 210, "unit": "piece", "category": "Regional - East India"},
    "Nolen Gurer Sandesh": {"calories": 130, "unit": "piece", "category": "Regional - East India"},
    "Shor Bhaja": {"calories": 200, "unit": "piece", "category": "Regional - East India"},
    "Dal Vada (Bengal)": {"calories": 200, "unit": "2 pieces", "category": "Regional - East India"},
    "Luchi Alur Dom": {"calories": 400, "unit": "serving (2 luchi)", "category": "Regional - East India"},
    "Ghugni (Bengal)": {"calories": 200, "unit": "cup", "category": "Regional - East India"},
    "Teler Pitha (Fried Rice Cake)": {"calories": 180, "unit": "piece", "category": "Regional - East India"},
    "Pithe (Rice Dumpling)": {"calories": 140, "unit": "piece", "category": "Regional - East India"},
    "Puri Sabzi (Odisha style)": {"calories": 350, "unit": "serving", "category": "Regional - East India"},
    "Dalma with Rice": {"calories": 400, "unit": "plate", "category": "Regional - East India"},

    # ─── MODERN & FAST FOOD ───────────────────────────────────────────────
    # Burgers & Sandwiches
    "Veg Burger": {"calories": 350, "unit": "piece", "category": "Modern & Fast Food"},
    "Paneer Burger": {"calories": 420, "unit": "piece", "category": "Modern & Fast Food"},
    "Aloo Tikki Burger": {"calories": 380, "unit": "piece", "category": "Modern & Fast Food"},
    "Veg Sandwich": {"calories": 250, "unit": "piece", "category": "Modern & Fast Food"},
    "Club Sandwich (Veg)": {"calories": 350, "unit": "piece", "category": "Modern & Fast Food"},
    "Grilled Cheese Sandwich": {"calories": 300, "unit": "piece", "category": "Modern & Fast Food"},
    "Egg Sandwich": {"calories": 280, "unit": "piece", "category": "Modern & Fast Food"},
    "Bombay Sandwich": {"calories": 280, "unit": "piece", "category": "Modern & Fast Food"},
    # Wraps & Rolls
    "Paneer Kathi Roll / Frankie": {"calories": 380, "unit": "piece", "category": "Modern & Fast Food"},
    "Aloo Kathi Roll": {"calories": 320, "unit": "piece", "category": "Modern & Fast Food"},
    "Egg Kathi Roll": {"calories": 350, "unit": "piece", "category": "Modern & Fast Food"},
    "Veg Wrap": {"calories": 300, "unit": "piece", "category": "Modern & Fast Food"},
    # Pizza
    "Veg Pizza (1 slice)": {"calories": 250, "unit": "slice", "category": "Modern & Fast Food"},
    "Paneer Pizza (1 slice)": {"calories": 290, "unit": "slice", "category": "Modern & Fast Food"},
    "Margherita Pizza (1 slice)": {"calories": 235, "unit": "slice", "category": "Modern & Fast Food"},
    # Noodles & Pasta
    "Maggi Noodles (1 pack cooked)": {"calories": 350, "unit": "serving", "category": "Modern & Fast Food"},
    "Yippee Noodles (1 pack)": {"calories": 340, "unit": "serving", "category": "Modern & Fast Food"},
    "Hakka Noodles (Veg)": {"calories": 380, "unit": "plate", "category": "Modern & Fast Food"},
    "Chow Mein (Veg)": {"calories": 360, "unit": "plate", "category": "Modern & Fast Food"},
    "Pasta (Veg, Red Sauce)": {"calories": 350, "unit": "plate", "category": "Modern & Fast Food"},
    "Pasta (Veg, White Sauce)": {"calories": 400, "unit": "plate", "category": "Modern & Fast Food"},
    "Mac and Cheese": {"calories": 400, "unit": "cup", "category": "Modern & Fast Food"},
    # Indo-Chinese
    "Veg Manchurian (Gravy)": {"calories": 250, "unit": "plate", "category": "Modern & Fast Food"},
    "Veg Manchurian (Dry)": {"calories": 200, "unit": "plate", "category": "Modern & Fast Food"},
    "Veg Spring Roll (fried)": {"calories": 120, "unit": "piece", "category": "Modern & Fast Food"},
    "Veg Momos / Dim Sum": {"calories": 200, "unit": "6 pieces", "category": "Modern & Fast Food"},
    "Schezwan Fried Rice (Veg)": {"calories": 380, "unit": "plate", "category": "Modern & Fast Food"},
    "Veg Fried Rice (Chinese)": {"calories": 350, "unit": "plate", "category": "Modern & Fast Food"},
    "American Chopsuey (Veg)": {"calories": 450, "unit": "plate", "category": "Modern & Fast Food"},
    "Veg Noodle Soup": {"calories": 150, "unit": "bowl", "category": "Modern & Fast Food"},
    "Sweet Corn Soup": {"calories": 120, "unit": "bowl", "category": "Modern & Fast Food"},
    "Tomato Soup": {"calories": 100, "unit": "bowl", "category": "Modern & Fast Food"},
    "Mushroom Soup": {"calories": 110, "unit": "bowl", "category": "Modern & Fast Food"},
    # Sides & others
    "French Fries": {"calories": 320, "unit": "serving", "category": "Modern & Fast Food"},
    "Aloo Wedges": {"calories": 280, "unit": "serving", "category": "Modern & Fast Food"},
    "Cheese Toast": {"calories": 200, "unit": "piece", "category": "Modern & Fast Food"},
    "Garlic Bread": {"calories": 180, "unit": "2 slices", "category": "Modern & Fast Food"},
    "Bread Upma": {"calories": 280, "unit": "cup", "category": "Modern & Fast Food"},
    "Bread Roll (fried, stuffed)": {"calories": 200, "unit": "piece", "category": "Modern & Fast Food"},
    "Veg Puff": {"calories": 200, "unit": "piece", "category": "Modern & Fast Food"},
    "Paneer Puff": {"calories": 230, "unit": "piece", "category": "Modern & Fast Food"},
    "Veg Lasagna": {"calories": 350, "unit": "serving", "category": "Modern & Fast Food"},

    # ─── BAKERY & BAKED GOODS ─────────────────────────────────────────────
    "Plain Cake (slice)": {"calories": 250, "unit": "slice", "category": "Bakery"},
    "Chocolate Cake (slice)": {"calories": 350, "unit": "slice", "category": "Bakery"},
    "Sponge Cake (slice)": {"calories": 270, "unit": "slice", "category": "Bakery"},
    "Carrot Cake (slice)": {"calories": 300, "unit": "slice", "category": "Bakery"},
    "Brownie": {"calories": 250, "unit": "piece", "category": "Bakery"},
    "Muffin (Plain)": {"calories": 250, "unit": "piece", "category": "Bakery"},
    "Muffin (Chocolate)": {"calories": 300, "unit": "piece", "category": "Bakery"},
    "Croissant": {"calories": 270, "unit": "piece", "category": "Bakery"},
    "Donut / Doughnut": {"calories": 280, "unit": "piece", "category": "Bakery"},
    "Pancake": {"calories": 180, "unit": "piece", "category": "Bakery"},
    "Waffle": {"calories": 220, "unit": "piece", "category": "Bakery"},
    "French Toast": {"calories": 200, "unit": "piece", "category": "Bakery"},
    # Biscuits & cookies
    "Marie Biscuit": {"calories": 70, "unit": "piece", "category": "Bakery"},
    "Digestive Biscuit": {"calories": 75, "unit": "piece", "category": "Bakery"},
    "Bourbon Biscuit": {"calories": 80, "unit": "piece", "category": "Bakery"},
    "Good Day Biscuit": {"calories": 65, "unit": "piece", "category": "Bakery"},
    "Glucose Biscuit": {"calories": 35, "unit": "piece", "category": "Bakery"},
    "Oreo (2 pieces)": {"calories": 100, "unit": "2 pieces", "category": "Bakery"},
    "Cream Cracker": {"calories": 60, "unit": "piece", "category": "Bakery"},
    "Parle-G (4 biscuits)": {"calories": 120, "unit": "4 pieces", "category": "Bakery"},
    "Chocolate Chip Cookie": {"calories": 150, "unit": "piece", "category": "Bakery"},
    # Chocolates
    "Dairy Milk (small 45g)": {"calories": 240, "unit": "bar", "category": "Bakery"},
    "KitKat (2 finger)": {"calories": 100, "unit": "piece", "category": "Bakery"},
    "Dark Chocolate (2 squares)": {"calories": 110, "unit": "2 squares", "category": "Bakery"},
    "5 Star (small)": {"calories": 130, "unit": "bar", "category": "Bakery"},
    "Munch (small)": {"calories": 100, "unit": "bar", "category": "Bakery"},

    # ─── SNACKS & STREET FOOD ─────────────────────────────────────────────
    "Samosa": {"calories": 250, "unit": "piece", "category": "Snacks"},
    "Kachori": {"calories": 230, "unit": "piece", "category": "Snacks"},
    "Pani Puri / Golgappa": {"calories": 200, "unit": "plate (6 pcs)", "category": "Snacks"},
    "Bhel Puri": {"calories": 180, "unit": "plate", "category": "Snacks"},
    "Sev Puri": {"calories": 200, "unit": "plate", "category": "Snacks"},
    "Dahi Puri": {"calories": 220, "unit": "plate", "category": "Snacks"},
    "Pav Bhaji": {"calories": 400, "unit": "plate", "category": "Snacks"},
    "Vada Pav": {"calories": 290, "unit": "piece", "category": "Snacks"},
    "Misal Pav": {"calories": 380, "unit": "plate", "category": "Snacks"},
    "Dabeli": {"calories": 250, "unit": "piece", "category": "Snacks"},
    "Dhokla": {"calories": 150, "unit": "2 pieces", "category": "Snacks"},
    "Khandvi": {"calories": 180, "unit": "4 pieces", "category": "Snacks"},
    "Handvo": {"calories": 200, "unit": "slice", "category": "Snacks"},
    "Chakli / Murukku": {"calories": 220, "unit": "4 pieces", "category": "Snacks"},
    "Namkeen / Mixture": {"calories": 400, "unit": "cup", "category": "Snacks"},
    "Pappad (plain)": {"calories": 50, "unit": "piece", "category": "Snacks"},
    "Roasted Peanuts": {"calories": 160, "unit": "handful", "category": "Snacks"},
    "Chikki (Peanut Brittle)": {"calories": 180, "unit": "piece", "category": "Snacks"},
    "Sev": {"calories": 400, "unit": "cup", "category": "Snacks"},
    "Corn Chaat": {"calories": 200, "unit": "cup", "category": "Snacks"},
    "Aloo Chaat": {"calories": 250, "unit": "plate", "category": "Snacks"},
    "Dahi Vada": {"calories": 220, "unit": "2 pieces", "category": "Snacks"},
    "Pakora / Bhajji": {"calories": 250, "unit": "cup", "category": "Snacks"},
    "Masala Peanuts": {"calories": 180, "unit": "handful", "category": "Snacks"},
    "Roasted Chana (Bhuna Chana)": {"calories": 150, "unit": "handful", "category": "Snacks"},
    "Kurmura / Puffed Rice": {"calories": 100, "unit": "cup", "category": "Snacks"},
    "Chivda": {"calories": 350, "unit": "cup", "category": "Snacks"},
    "Mathri": {"calories": 200, "unit": "4 pieces", "category": "Snacks"},
    "Shakarpara": {"calories": 220, "unit": "cup", "category": "Snacks"},
    "Bread Pakora": {"calories": 300, "unit": "piece", "category": "Snacks"},
    "Paneer Tikka": {"calories": 280, "unit": "serving (4 pieces)", "category": "Snacks"},
    "Hara Bhara Kabab": {"calories": 150, "unit": "2 pieces", "category": "Snacks"},
    "Corn Bhel": {"calories": 190, "unit": "plate", "category": "Snacks"},
    "Makhana (Fox Nuts Roasted)": {"calories": 100, "unit": "cup", "category": "Snacks"},
    "Trail Mix (Dry Fruits & Nuts)": {"calories": 200, "unit": "handful", "category": "Snacks"},
    "Almonds": {"calories": 170, "unit": "handful (20 pieces)", "category": "Snacks"},
    "Cashews": {"calories": 180, "unit": "handful", "category": "Snacks"},
    "Walnuts": {"calories": 190, "unit": "handful", "category": "Snacks"},
    "Pistachios": {"calories": 160, "unit": "handful", "category": "Snacks"},
    "Banana Chips": {"calories": 350, "unit": "cup", "category": "Snacks"},
    "Sweet Corn (boiled)": {"calories": 100, "unit": "cup", "category": "Snacks"},
    "Popcorn (plain)": {"calories": 100, "unit": "cup", "category": "Snacks"},
    "Popcorn (butter)": {"calories": 150, "unit": "cup", "category": "Snacks"},
    "Popcorn (caramel)": {"calories": 200, "unit": "cup", "category": "Snacks"},
    "Potato Wafers / Chips (small pack)": {"calories": 150, "unit": "pack", "category": "Snacks"},
    "Kurkure / Cheetos (small pack)": {"calories": 140, "unit": "pack", "category": "Snacks"},
    "Lays (small pack)": {"calories": 140, "unit": "pack", "category": "Snacks"},
    "Masala Oats": {"calories": 180, "unit": "cup", "category": "Snacks"},
    "Granola Bar": {"calories": 200, "unit": "bar", "category": "Snacks"},
    "Energy Bar (Protein)": {"calories": 220, "unit": "bar", "category": "Snacks"},
    "Peanut Butter (on bread)": {"calories": 190, "unit": "slice with tbsp PB", "category": "Snacks"},
    "Peanut Butter": {"calories": 95, "unit": "tbsp", "category": "Snacks"},
    "Rusk": {"calories": 80, "unit": "piece", "category": "Snacks"},
    "Bread (with butter & jam)": {"calories": 200, "unit": "2 slices", "category": "Snacks"},
    "Chaat Masala Fruit Salad": {"calories": 100, "unit": "cup", "category": "Snacks"},
    "Boiled Egg with Salt": {"calories": 78, "unit": "piece", "category": "Snacks"},
    "Cucumber with Salt & Lemon": {"calories": 20, "unit": "cup", "category": "Snacks"},
    "Carrot Sticks": {"calories": 30, "unit": "cup", "category": "Snacks"},

    # ─── FRUITS ───────────────────────────────────────────────────────────
    "Banana": {"calories": 90, "unit": "piece", "category": "Fruits"},
    "Apple": {"calories": 80, "unit": "medium piece", "category": "Fruits"},
    "Orange": {"calories": 60, "unit": "piece", "category": "Fruits"},
    "Mango": {"calories": 100, "unit": "cup sliced", "category": "Fruits"},
    "Guava": {"calories": 50, "unit": "piece", "category": "Fruits"},
    "Papaya": {"calories": 60, "unit": "cup", "category": "Fruits"},
    "Watermelon": {"calories": 45, "unit": "cup", "category": "Fruits"},
    "Grapes": {"calories": 90, "unit": "cup", "category": "Fruits"},
    "Pomegranate": {"calories": 83, "unit": "cup", "category": "Fruits"},
    "Pineapple": {"calories": 80, "unit": "cup", "category": "Fruits"},
    "Chickoo / Sapota": {"calories": 100, "unit": "piece", "category": "Fruits"},
    "Dates": {"calories": 110, "unit": "4 pieces", "category": "Fruits"},
    "Coconut (fresh)": {"calories": 160, "unit": "cup grated", "category": "Fruits"},
    "Strawberry": {"calories": 50, "unit": "cup", "category": "Fruits"},
    "Pear": {"calories": 75, "unit": "piece", "category": "Fruits"},
    "Peach": {"calories": 60, "unit": "piece", "category": "Fruits"},
    "Plum": {"calories": 45, "unit": "piece", "category": "Fruits"},
    "Kiwi": {"calories": 42, "unit": "piece", "category": "Fruits"},
    "Custard Apple (Sitaphal)": {"calories": 100, "unit": "cup", "category": "Fruits"},
    "Jamun (Indian Blackberry)": {"calories": 60, "unit": "cup", "category": "Fruits"},
    "Lychee": {"calories": 65, "unit": "cup", "category": "Fruits"},
    "Jackfruit (ripe)": {"calories": 95, "unit": "cup", "category": "Fruits"},
    "Wood Apple (Bael)": {"calories": 100, "unit": "medium fruit", "category": "Fruits"},
    "Amla / Indian Gooseberry": {"calories": 45, "unit": "piece", "category": "Fruits"},
    "Tamarind (ripe)": {"calories": 115, "unit": "handful", "category": "Fruits"},
    "Fig (Anjeer) fresh": {"calories": 74, "unit": "2 pieces", "category": "Fruits"},
    "Fig (Anjeer) dried": {"calories": 125, "unit": "3 pieces", "category": "Fruits"},
    "Dried Mango (Aamchur)": {"calories": 100, "unit": "handful", "category": "Fruits"},
    "Raisins (Kishmish)": {"calories": 130, "unit": "handful", "category": "Fruits"},
    "Prunes (dried plum)": {"calories": 100, "unit": "4 pieces", "category": "Fruits"},
    "Apricot (dried)": {"calories": 85, "unit": "5 pieces", "category": "Fruits"},
    "Mixed Dried Fruits": {"calories": 150, "unit": "handful", "category": "Fruits"},
    "Avocado": {"calories": 160, "unit": "half fruit", "category": "Fruits"},
    "Passion Fruit": {"calories": 50, "unit": "piece", "category": "Fruits"},
    "Dragon Fruit": {"calories": 60, "unit": "cup", "category": "Fruits"},

    # ─── SWEETS & DESSERTS ────────────────────────────────────────────────
    "Gulab Jamun": {"calories": 175, "unit": "piece", "category": "Sweets"},
    "Rasgulla": {"calories": 120, "unit": "piece", "category": "Sweets"},
    "Rasmalai": {"calories": 150, "unit": "piece", "category": "Sweets"},
    "Ladoo (Besan)": {"calories": 200, "unit": "piece", "category": "Sweets"},
    "Ladoo (Boondi)": {"calories": 180, "unit": "piece", "category": "Sweets"},
    "Ladoo (Motichoor)": {"calories": 185, "unit": "piece", "category": "Sweets"},
    "Ladoo (Coconut / Kobbari)": {"calories": 170, "unit": "piece", "category": "Sweets"},
    "Ladoo (Churma)": {"calories": 220, "unit": "piece", "category": "Sweets"},
    "Halwa (Suji/Rava)": {"calories": 350, "unit": "cup", "category": "Sweets"},
    "Halwa (Gajar/Carrot)": {"calories": 300, "unit": "cup", "category": "Sweets"},
    "Halwa (Moong Dal)": {"calories": 380, "unit": "cup", "category": "Sweets"},
    "Halwa (Atta/Wheat)": {"calories": 360, "unit": "cup", "category": "Sweets"},
    "Halwa (Chana Dal)": {"calories": 370, "unit": "cup", "category": "Sweets"},
    "Kheer / Rice Pudding": {"calories": 250, "unit": "cup", "category": "Sweets"},
    "Sevai / Vermicelli Kheer": {"calories": 240, "unit": "cup", "category": "Sweets"},
    "Payasam": {"calories": 280, "unit": "cup", "category": "Sweets"},
    "Jalebi": {"calories": 150, "unit": "piece", "category": "Sweets"},
    "Imarti": {"calories": 200, "unit": "piece", "category": "Sweets"},
    "Peda": {"calories": 120, "unit": "piece", "category": "Sweets"},
    "Barfi (Milk Cake / Plain)": {"calories": 150, "unit": "piece", "category": "Sweets"},
    "Besan Barfi": {"calories": 160, "unit": "piece", "category": "Sweets"},
    "Mysore Pak": {"calories": 200, "unit": "piece", "category": "Sweets"},
    "Kaju Katli": {"calories": 130, "unit": "piece", "category": "Sweets"},
    "Modak (Fried)": {"calories": 180, "unit": "piece", "category": "Sweets"},
    "Modak (Steamed)": {"calories": 120, "unit": "piece", "category": "Sweets"},
    "Pongal (Sweet / Chakkarai)": {"calories": 320, "unit": "cup", "category": "Sweets"},
    "Ice Cream": {"calories": 200, "unit": "scoop", "category": "Sweets"},
    "Kulfi": {"calories": 150, "unit": "piece", "category": "Sweets"},
    "Sandesh (Bengali)": {"calories": 120, "unit": "piece", "category": "Sweets"},
    "Rasgulla (large)": {"calories": 140, "unit": "piece", "category": "Sweets"},
    "Patishapta (Bengali crepe)": {"calories": 190, "unit": "piece", "category": "Sweets"},
    "Mishti Doi": {"calories": 150, "unit": "cup", "category": "Sweets"},
    "Chhena Poda": {"calories": 300, "unit": "piece", "category": "Sweets"},
    "Ras Malai": {"calories": 160, "unit": "piece", "category": "Sweets"},
    "Kalakand": {"calories": 170, "unit": "piece", "category": "Sweets"},
    "Sohan Papdi": {"calories": 160, "unit": "piece", "category": "Sweets"},
    "Petha": {"calories": 100, "unit": "piece", "category": "Sweets"},
    "Coconut Burfi": {"calories": 160, "unit": "piece", "category": "Sweets"},
    "Til Chikki": {"calories": 180, "unit": "piece", "category": "Sweets"},
    "Peanut Chikki": {"calories": 180, "unit": "piece", "category": "Sweets"},
    "Badam Halwa": {"calories": 400, "unit": "cup", "category": "Sweets"},

    # ─── SALADS & SIDES ───────────────────────────────────────────────────
    "Green Salad": {"calories": 30, "unit": "plate", "category": "Salads & Sides"},
    "Kachumber Salad": {"calories": 40, "unit": "cup", "category": "Salads & Sides"},
    "Sprouts Salad": {"calories": 100, "unit": "cup", "category": "Salads & Sides"},
    "Onion Salad": {"calories": 40, "unit": "cup", "category": "Salads & Sides"},
    "Cucumber Salad": {"calories": 30, "unit": "cup", "category": "Salads & Sides"},
    "Carrot Salad": {"calories": 50, "unit": "cup", "category": "Salads & Sides"},
    "Pickle (Achar)": {"calories": 30, "unit": "tbsp", "category": "Salads & Sides"},
    "Chutney (Mint)": {"calories": 15, "unit": "tbsp", "category": "Salads & Sides"},
    "Chutney (Coconut)": {"calories": 50, "unit": "tbsp", "category": "Salads & Sides"},
    "Chutney (Tomato)": {"calories": 25, "unit": "tbsp", "category": "Salads & Sides"},
    "Chutney (Gongura)": {"calories": 20, "unit": "tbsp", "category": "Salads & Sides"},
    "Pappad (Fried)": {"calories": 70, "unit": "piece", "category": "Salads & Sides"},
    "Pappad (Roasted)": {"calories": 35, "unit": "piece", "category": "Salads & Sides"},
    "Ghee": {"calories": 45, "unit": "tsp", "category": "Salads & Sides"},
    "Butter": {"calories": 36, "unit": "tsp", "category": "Salads & Sides"},
    "Oil (cooking)": {"calories": 40, "unit": "tsp", "category": "Salads & Sides"},
    "Coconut Chutney (full serving)": {"calories": 80, "unit": "serving", "category": "Salads & Sides"},
    "Peanut Chutney": {"calories": 90, "unit": "serving", "category": "Salads & Sides"},
}

MEAL_PERIODS = ["Breakfast", "Lunch", "Dinner", "Snack / Anytime"]

CATEGORIES = sorted(set(v["category"] for v in FOOD_DATABASE.values()))

def get_foods_by_category(category: str) -> dict:
    return {k: v for k, v in FOOD_DATABASE.items() if v["category"] == category}

def get_all_food_names() -> list:
    return sorted(FOOD_DATABASE.keys())

def get_food_info(food_name: str) -> dict:
    return FOOD_DATABASE.get(food_name, {})
